#!/bin/bash
#
#     betteraxe <filename> <search-string>
#
# DESCRIPTION
#     Finds commits where a particular string was introduced and removed from
#     a file in a git repository.
#
#     In certain cases involving merge commits, it's possible a line
#     disappears in a way that git-pickaxe won't report on. This tool will
#     catch this case and report the exact commits that caused a line with a
#     string to be introduced and then removed.
#
# AUTHOR
#     Rick Harris <rconradharris@gmail.com>
COLOR_GREEN='\e[0;32m'
COLOR_RED='\e[0;31m'
COLOR_YELLOW='\e[0;33m'
COLOR_END='\e[0m'

FILE=$1
SEARCH_STRING=$2
if [[ -z $FILE || -z $SEARCH_STRING ]]; then
    echo "usage: betteraxe <filename> <search-string>"
    exit 1
fi

LAST_MATCH=
HASHES=`git log --topo-order --reverse --pretty='%H' -- $FILE`
for hash in $HASHES; do
    match=$(git show $hash:$FILE 2> /dev/null | grep $SEARCH_STRING)

    if [[ -n $match ]]; then

        if [[ -z $LAST_MATCH ]]; then
            echo -e "${COLOR_GREEN}A $hash $match${COLOR_END}"
        elif [[ $match == $LAST_MATCH ]]; then
            echo -e "S $hash $match"
        else
            echo -e "${COLOR_YELLOW}U $hash $match${COLOR_END}"
        fi
    else

        if [[ -n $LAST_MATCH ]]; then
            echo -e "${COLOR_RED}D $hash $match${COLOR_END}"
        fi
    fi

    LAST_MATCH=$match
done
